---

- name: DEPLOY A3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

  vars_files:
  - ../creds/credentials.json

  tasks:
  - name: Deploy pplication Service
    uri:
      url: https://20.0.58.197:8443/mgmt/shared/appsvcs/declare
      user: "{{ username }}"
      password: "{{ password }}"
      method: POST
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_output

  - name: EBUG OUTPUT
    debug:
     msg: "output event info {{ as3_output }}"

...